const fs = require('fs');
const crypto = require('crypto');
const readline = require('readline');
let wasm, heap = new Array(1024).fill(undefined), heap_next, cachedUint8=null, cachedDataView=null, WASM_VECTOR_LEN=0;
heap.push(undefined,null,true,false); heap_next=heap.length;
const textEncoder=new TextEncoder(); const textDecoder=new TextDecoder('utf-8',{ignoreBOM:true,fatal:true}); textDecoder.decode();
function getUint8(){ if(cachedUint8===null||cachedUint8.byteLength===0) cachedUint8=new Uint8Array(wasm.memory.buffer); return cachedUint8; }
function getDataView(){ if(cachedDataView===null||cachedDataView.buffer!==wasm.memory.buffer) cachedDataView=new DataView(wasm.memory.buffer); return cachedDataView; }
function addHeapObject(obj){ if(heap_next===heap.length) heap.push(heap.length+1); const idx=heap_next; heap_next=heap[idx]; heap[idx]=obj; return idx; }
function getObject(idx){ return heap[idx]; }
function takeObject(idx){ const ret=heap[idx]; if(idx>=1028){ heap[idx]=heap_next; heap_next=idx; } return ret; }
function getString(p,l){ p>>>=0; return textDecoder.decode(getUint8().subarray(p,p+l)); }
function passArray8(arr,malloc){ const p=malloc(arr.length,1)>>>0; getUint8().set(arr,p); WASM_VECTOR_LEN=arr.length; return p; }
function passString(str,malloc,realloc){
 if(realloc===undefined){ const b=textEncoder.encode(str); const p=malloc(b.length,1)>>>0; getUint8().subarray(p,p+b.length).set(b); WASM_VECTOR_LEN=b.length; return p; }
 let len=str.length, p=malloc(len,1)>>>0, mem=getUint8(), off=0;
 for(;off<len;off++){ const code=str.charCodeAt(off); if(code>127) break; mem[p+off]=code; }
 if(off!==len){ if(off!==0) str=str.slice(off); p=realloc(p,len,len=off+str.length*3,1)>>>0; const view=getUint8().subarray(p+off,p+len); const ret=textEncoder.encodeInto(str,view); off+=ret.written; p=realloc(p,len,off,1)>>>0; }
 WASM_VECTOR_LEN=off; return p;
}
function handleError(f,args){ try{return f.apply(this,args)}catch(e){ wasm.__wbindgen_export(addHeapObject(e)); } }
const imports={'./hdh_security_bg.js':{
 __wbg_Error_ef53bc310eb298a0:(p,l)=>addHeapObject(Error(getString(p,l))), __wbg___wbindgen_is_function_754e9f305ff6029e:i=>typeof getObject(i)==='function', __wbg___wbindgen_is_object_56732c2bc353f41d:i=>{const o=getObject(i);return typeof o==='object'&&o!==null}, __wbg___wbindgen_is_string_c236cabd84a4d769:i=>typeof getObject(i)==='string', __wbg___wbindgen_is_undefined_67b456be8673d3d7:i=>getObject(i)===undefined, __wbg___wbindgen_throw_1506f2235d1bdba0:(p,l)=>{throw Error(getString(p,l))}, __wbg_call_9c758de292015997:function(){return handleError((a,b,c)=>addHeapObject(getObject(a).call(getObject(b),getObject(c))),arguments)}, __wbg_crypto_38df2bab126b63dc:i=>addHeapObject(getObject(i).crypto), __wbg_getRandomValues_c44a50d8cfdaebeb:function(){return handleError((a,b)=>getObject(a).getRandomValues(getObject(b)),arguments)}, __wbg_length_4a591ecaa01354d9:i=>getObject(i).length, __wbg_msCrypto_bd5a034af96bcba6:i=>addHeapObject(getObject(i).msCrypto), __wbg_new_with_length_36a4998e27b014c5:len=>addHeapObject(new Uint8Array(len>>>0)), __wbg_node_84ea875411254db1:i=>addHeapObject(getObject(i).node), __wbg_process_44c7a14e11e9f69e:i=>addHeapObject(getObject(i).process), __wbg_prototypesetcall_3249fc62a0fafa30:(a,b,c)=>Uint8Array.prototype.set.call(getUint8().subarray(a>>>0,(a>>>0)+b),getObject(c)), __wbg_randomFillSync_6c25eac9869eb53c:function(){return handleError((a,b)=>getObject(a).randomFillSync(takeObject(b)),arguments)}, __wbg_require_b4edbdcf3e2a1ef0:function(){return handleError(()=>addHeapObject(require),arguments)}, __wbg_static_accessor_GLOBAL_9d53f2689e622ca1:()=>addHeapObject(global), __wbg_static_accessor_GLOBAL_THIS_a1a35cec07001a8a:()=>addHeapObject(globalThis), __wbg_static_accessor_SELF_4c59f6c7ea29a144:()=>0, __wbg_static_accessor_WINDOW_e70ae9f2eb052253:()=>0, __wbg_subarray_4aa221f6a4f5ab22:(a,b,c)=>addHeapObject(getObject(a).subarray(b>>>0,c>>>0)), __wbg_versions_276b2795b1c6a219:i=>addHeapObject(getObject(i).versions), __wbindgen_cast_0000000000000001:(p,l)=>addHeapObject(getUint8().subarray(p>>>0,(p>>>0)+l)), __wbindgen_cast_0000000000000002:(p,l)=>addHeapObject(getString(p,l)), __wbindgen_object_clone_ref:i=>addHeapObject(getObject(i)), __wbindgen_object_drop_ref:i=>{takeObject(i)}
}};
function initWasm(path){ const bytes=fs.readFileSync(path); const mod=new WebAssembly.Module(bytes); const inst=new WebAssembly.Instance(mod,imports); wasm=inst.exports; cachedUint8=null; cachedDataView=null; }
function wasmInit(){ const sp=wasm.__wbindgen_add_to_stack_pointer(-16); try{ wasm.init(sp); const dv=getDataView(); const p=dv.getInt32(sp,true), l=dv.getInt32(sp+4,true), err=dv.getInt32(sp+8,true); if(dv.getInt32(sp+12,true)) throw takeObject(err); const ret=getUint8().subarray(p,p+l).slice(); wasm.__wbindgen_export4(p,l,1); return ret; } finally{ wasm.__wbindgen_add_to_stack_pointer(16); } }
function finalize(cid,serverPub,kid=1){ const sp=wasm.__wbindgen_add_to_stack_pointer(-16); try{ const p1=passString(cid,wasm.__wbindgen_export2,wasm.__wbindgen_export3), l1=WASM_VECTOR_LEN; const p2=passArray8(serverPub,wasm.__wbindgen_export2), l2=WASM_VECTOR_LEN; wasm.finalizeHandshake(sp,p1,l1,p2,l2,kid); const dv=getDataView(); const err=dv.getInt32(sp,true); if(dv.getInt32(sp+4,true)) throw takeObject(err); } finally{ wasm.__wbindgen_add_to_stack_pointer(16); } }
function sign(method,path,ts,nonce,body,userId){ const sp=wasm.__wbindgen_add_to_stack_pointer(-16); let rp=0,rl=0; try{ const p1=passString(method,wasm.__wbindgen_export2,wasm.__wbindgen_export3), l1=WASM_VECTOR_LEN; const p2=passString(path,wasm.__wbindgen_export2,wasm.__wbindgen_export3), l2=WASM_VECTOR_LEN; const p3=passString(ts,wasm.__wbindgen_export2,wasm.__wbindgen_export3), l3=WASM_VECTOR_LEN; const p4=passString(nonce,wasm.__wbindgen_export2,wasm.__wbindgen_export3), l4=WASM_VECTOR_LEN; const p5=passArray8(body,wasm.__wbindgen_export2), l5=WASM_VECTOR_LEN; const p6=passString(userId,wasm.__wbindgen_export2,wasm.__wbindgen_export3), l6=WASM_VECTOR_LEN; wasm.signRequest(sp,p1,l1,p2,l2,p3,l3,p4,l4,p5,l5,p6,l6); const dv=getDataView(); const p=dv.getInt32(sp,true), l=dv.getInt32(sp+4,true), err=dv.getInt32(sp+8,true); if(dv.getInt32(sp+12,true)) throw takeObject(err); rp=p; rl=l; return getString(p,l); } finally{ wasm.__wbindgen_add_to_stack_pointer(16); wasm.__wbindgen_export4(rp,rl,1); } }
function emit(o){ process.stdout.write(JSON.stringify(o)+'\n'); }
async function main(){
 const cfg=JSON.parse(process.argv[2]||'{}'); initWasm(cfg.wasmPath||'hdh_security_bg.wasm');
 const ua=cfg.userAgent||'', lang=cfg.languages||'zh-CN,zh'; const clientPub=wasmInit(); const fp=crypto.createHash('sha256').update(`${ua}|${lang}`).digest('hex'); emit({type:'init', client_pub:Buffer.from(clientPub).toString('base64'), ua_fingerprint:fp, ts:Date.now()});
 const rl=readline.createInterface({input:process.stdin, crlfDelay:Infinity});
 for await (const line of rl){ if(!line.trim()) continue; const input=JSON.parse(line); if(input.server_pub&&input.cid) finalize(input.cid,Buffer.from(input.server_pub,'base64'),1); const ts=String(input.ts||Date.now()), nonce=input.nonce||crypto.randomBytes(16).toString('hex'); const body=input.body_b64?Buffer.from(input.body_b64,'base64'):Buffer.from(input.body||''); const sig=sign((input.method||'GET').toUpperCase(), input.path, ts, nonce, body, String(input.userId||'0')); emit({type:'sig', ts, nonce, sig, cid:input.cid, kid:'1'}); }
}
main().catch(e=>{console.error(e&&e.stack||String(e)); process.exit(1);});
